### ISSUE TITLE
needs a license file and clear copyright/license notice on individual files.

### ISSUE THREAD

**Issue by jeske** [xexuxjy/bullet-xna#22]

**Comment by AndresTraks** [comment]
Preferably the zlib license, to match Bullet.

To avoid clutter, I'd also prefer a license file in the root directory over having it in individual files, especially if the license is permissive.

**Comment by jeske** [comment]
It is important that (most) files have some form of copyright and license reference, even if is just a short note that just says "Copyright (C) Author Name, released under zlib license. See license.txt"

**Comment by AndresTraks** [comment]
That's ok too. :)

**Comment by xexuxjy** [comment]
I'll looks at the current bullet licenses and bring it in line. (unless Andres has already done it)

Thanks.

**Comment by xexuxjy** [comment]
Should all be sorted now. Please let me know if not.
